SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE `member`;
TRUNCATE TABLE `project`;
TRUNCATE TABLE `project_member`;
TRUNCATE TABLE `module`;
TRUNCATE TABLE `kanbanboard`;
TRUNCATE TABLE `label`;
TRUNCATE TABLE `issue`;
TRUNCATE TABLE `api_specification`;
TRUNCATE TABLE `domain`;
TRUNCATE TABLE `api`;
TRUNCATE TABLE `http_method`;

SET FOREIGN_KEY_CHECKS=1;
